### ISSUE TITLE
请问示例数据中，如何确定相机拍照的分辨率呢

### ISSUE THREAD

**Issue by EulerWong** [Livox-SDK/livox_camera_lidar_calibration#11]
示例数据中拍摄的照片的分辨都是 1148 x 568， 请问这个分辨率是对摄像头拍摄的照片进行过缩放了吗？为什么我设置成 2896 x 1136就出错呢？

![image](https://user-images.githubusercontent.com/6688986/94415405-13068b80-01b0-11eb-888b-f7c6f394b288.png)

**Comment by Livox-SDK** [comment]
是的我们是根据horizon lidar的FOV剪裁了一下相机的FOV,设置成别的分辨率需要重新调整相机的内参并且重新采集照片的角点坐标

**Comment by zcl912** [comment]
> 示例数据中拍摄的照片的分辨都是 1148 x 568， 请问这个分辨率是对摄像头拍摄的照片进行过缩放了吗？为什么我设置成 2896 x 1136就出错呢？
> 
> ![image](https://user-images.githubusercontent.com/6688986/94415405-13068b80-01b0-11eb-888b-f7c6f394b288.png)

示例数据能分享一下吗，现在下载不了
