### ISSUE TITLE
想知道怎麼從FOV算出image dimension

### ISSUE THREAD

**Issue by isaackc** [Livox-SDK/livox_camera_lidar_calibration#12]
"The photo dimension needs to be modified according to the FOV(field of view) of LiDAR, the Horizon ’s FOV is 81.7 (horizontal) x 25.1 (vertical), so the photos used in this case have a dimension of 1520 (width) x 568 (height) pixels."

我買了一個 livox mix-40﹐想知道怎麼從它的38.4° Circular FOV算出image dimension. 謝謝。

**Comment by cccdddwww** [comment]
我拍的照片是640(width)x480 (height)，最后把雷达点云投影到照片上也是ok的，只不过是照片上除了fov以外的地方都没投影罢了

**Comment by Livox-SDK** [comment]
直接算可能不是很方便,我们建议在雷达和相机固定之后,选择一个合适的场景同时打开雷达和相机的上位机显示实时的图像,然后根据雷达视角里面的物体直接剪裁相机的FOV,直到它们能包含同样的场景.这样操作会比较方便一些
