### ISSUE TITLE
cameraCalib.launch 里面的参数文件问题

### ISSUE THREAD

**Issue by xielinjiang** [Livox-SDK/livox_camera_lidar_calibration#13]
cameraCalib.launch 里的参数文件，row_number 和 col_number 是不是搞反了？

**Comment by Livox-SDK** [comment]
啊哈哈,是的是的 有一点歧义; 发现我们当时写的row_number/col_number 实际上指的是 一行/列上有多少个格子 具体定义请以后面的注释为准哈~
