### ISSUE TITLE
关于标定中录制的customMsg格式的rosbag

### ISSUE THREAD

**Issue by cccdddwww** [Livox-SDK/livox_camera_lidar_calibration#14]
请问录制下来的customMsg格式rosbag想用rviz播放要怎么做

**Comment by Livox-SDK** [comment]
你好 cccdddwww,
rogbag播放请参考这个链接
https://livox-wiki-cn.readthedocs.io/zh_CN/latest/tutorials/format_conversion.html#livox-lidar
需要改一下 rviz 设置里的topic 和 frame 的设置就可以播放了
