### ISSUE TITLE
Coordinates not displayed using cornerPhoto

### ISSUE THREAD

**Issue by VisionaryMind** [Livox-SDK/livox_camera_lidar_calibration#15]
Using your sample data as a test, the cornerPhoto launch file opens the first image, but no coordinates are displayed:

![image](https://user-images.githubusercontent.com/47434136/105202992-6c941c80-5af7-11eb-9a33-3173f5d3a2b2.png)

Where can the setting be found for enabling coordinate display?

**Comment by VisionaryMind** [comment]
This is a problem with not having OpenCV 4 in Ubuntu 18.04. ROS Melodic uses OpenCV 3.2 by default, so it is necessary to uninstall the Core 3.2 libopencv libraries and manually compile the ROS workspace for OpenCV4.

**Comment by rahulsharma11** [comment]
Hi, I am using ros noetic with opencv4.2

Still my issue is same. I am not able to see the coordinates in bottom of image.

**Comment by ZYJxxx** [comment]
> Hi, I am using ros noetic with opencv4.2
> 
> Still my issue is same. I am not able to see the coordinates in bottom of image.

hi, have you solved it?

**Comment by Ri-Bai** [comment]
> This is a problem with not having OpenCV 4 in Ubuntu 18.04. ROS Melodic uses OpenCV 3.2 by default, so it is necessary to uninstall the Core 3.2 libopencv libraries and manually compile the ROS workspace for OpenCV4.

Hello,I use opencv4.0  but no cordinate no display.which opencv are you use?

**Comment by Ri-Bai** [comment]
> > Hi, I am using ros noetic with opencv4.2
> > Still my issue is same. I am not able to see the coordinates in bottom of image.
> 
> hi, have you solved it?

 hello,have you solved this problem?

**Comment by 1010186** [comment]
有人解决了吗，is there anyone solved it？who can help children?
