### ISSUE TITLE
关于摄像机配置

### ISSUE THREAD

**Issue by CARASO** [Livox-SDK/livox_camera_lidar_calibration#18]
为什么我用这个型号的摄像机采到的图像光线很弱，黑乎乎的。对镜头有指定吗？或者需要额外配什么光源吗？还是说有别的参数需要配置？

**Comment by EulerWong** [comment]
肯定是你曝光时间设置不对。你可以在MVS里设置自动曝光时间。

工业相机都这样的， 又贵效果又不好，还没手机摄像头的效果好呢。

我用的沃乐斯4mm镜头，畸变太大了，虽然进行了相机标定了，但点云点照片还是不能完美对其，有漂移。

为了匹配mid-70的FOV，只能选4mm镜头了，6mm的镜头FOV比MID-70的小，但是镜头畸变有点大。
