### ISSUE TITLE
运行 roslaunch camera_lidar_calibration cameraCalib.launch的时候报错

### ISSUE THREAD

**Issue by yuyu19970716** [Livox-SDK/livox_camera_lidar_calibration#27]
你好，我在运行 roslaunch camera_lidar_calibration cameraCalib.launch的时候报错：
ERROR: cannot launch node of type [camera_lidar_calibration/cameraCalib]: Cannot locate node of type [cameraCalib] in package [camera_lidar_calibration]. Make sure file exists in package path and permission is set to executable (chmod +x)

可是我修改了文件的权限并且文件确实存在，为什么会报这个错呢？

**Comment by KiriyuMoka** [comment]
怎么解决的啊
