### ISSUE TITLE
Camera type

### ISSUE THREAD

**Issue by Camilochiang** [Livox-SDK/livox_camera_lidar_calibration#28]
Good day.
Why does the camera need to be a "pinhole imaging model" ? isn't possible to use a normal camera with fix focus length?

Thanks in advance!

**Comment by Livox-SDK** [comment]
Hi Camilochiang, 

I think since the optimization logic of the camera is based on pinhole imaging model, That's the reason we used this model here.

**Comment by BellosC** [comment]
Thank you for the answer but can we use a normal camera with fix focus length or not with this package?

**Comment by Camilochiang** [comment]
I believe that is the case. if you keep your camera with fix focus (infinite hopefully) It should work, as in that configuration it is basically working as a pin hole camera. I will try and let you know ;)

**Comment by BellosC** [comment]
thank you
 @Camilochiang
