### ISSUE TITLE
Hi, I've got an issue in step 4.2

### ISSUE THREAD

**Issue by Minsu-Kim1822** [Livox-SDK/livox_camera_lidar_calibration#35]
Hi, I want to ask something in this repo.

In step 4.2, our cursor could get x, y coords in image, but In my case, I cannot get coordiinates. Is there any solutions??

**Comment by qulei123** [comment]
I also encountered the problem, how to solve it

**Comment by Minsu-Kim1822** [comment]
I just try to solve it with OpenCV Mouse position tracking function. Same  input image and just get x, y position with tracking code.

**Comment by qulei123** [comment]
You can use the link above to get the project source code，Updated Photo corner picker to more user friendly version.
https://github.com/kaanoguzhan/livox_camera_lidar_calibration

**Comment by Minsu-Kim1822** [comment]
OMG Thanks. It works well..!
