### ISSUE TITLE
解决了吗

### ISSUE THREAD

**Issue by 1010186** [Livox-SDK/livox_camera_lidar_calibration#51]
我也有这个问题，ubuntu18.04下，获取角点数据时，不显示坐标，底栏信息，不能进行下一步，

_Originally posted by @blackusagi in https://github.com/Livox-SDK/livox_camera_lidar_calibration/issues/32#issuecomment-1004277478_

**Comment by mei123456789** [comment]
你好，我也遇到了这个问题，请问你是如何解决的，希望得到你的回复，谢谢

**Comment by blackusagi** [comment]
没有解决，最后使用matlab完成了标定
