### ISSUE TITLE
请问能否实现在loam建图的同时，对点云进行上色

### ISSUE THREAD

**Issue by SEU-zhc** [Livox-SDK/livox_camera_lidar_calibration#6]
根据这个项目的教学，已经可以实现使用照片对静态的点云进行上色
请问能否实现在loam建图的同时，对点云进行上色呢？

非常感谢！

**Comment by Livox-SDK** [comment]
是可以在Loam建图的时候上色的，只要做了相机和雷达的同步，每一帧点云可以找到对应的图像来获得色彩后再建图即可。Loam建图和雷达相机同步都可以参考我们的开源算法和SDK中的教程，希望你能获得好的效果！

**Comment by JandonXi** [comment]
你好请问看雷达相机同步的教程具体在哪里？
非常感谢

**Comment by SEU-zhc** [comment]
readme里面描述的非常清晰了呀

---原始邮件---
发件人: "Jandon xi"<notifications@github.com&gt;
发送时间: 2020年9月26日(周六) 晚上9:59
收件人: "Livox-SDK/livox_camera_lidar_calibration"<livox_camera_lidar_calibration@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"cctge123"<66011@qq.com&gt;;
主题: Re: [Livox-SDK/livox_camera_lidar_calibration] 请问能否实现在loam建图的同时，对点云进行上色 (#6)




 
你好请问看雷达相机同步的教程具体在哪里？
 非常感谢

**Comment by JandonXi** [comment]
我指雷达相机的时间同步，请问在readme的哪里？真没有找到 ：）

**Comment by SEU-zhc** [comment]
这个项目提供了把点云映射到二维图像上的功能。时间同步这些得自己写



---原始邮件---
发件人: "Jandon xi"<notifications@github.com&gt;
发送时间: 2020年9月26日(周六) 晚上10:08
收件人: "Livox-SDK/livox_camera_lidar_calibration"<livox_camera_lidar_calibration@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"cctge123"<66011@qq.com&gt;;
主题: Re: [Livox-SDK/livox_camera_lidar_calibration] 请问能否实现在loam建图的同时，对点云进行上色 (#6)




 
我指雷达相机的时间同步，请问在readme的哪里？真没有找到 ：）

**Comment by JandonXi** [comment]
：）是的是的，对了，你使用projectCloud这个节点有遇到问题吗，详细的可以看我被折叠的request.

**Comment by SEU-zhc** [comment]
我没遇到问题。。正常运行，你遇到什么问题



---原始邮件---
发件人: "Jandon xi"<notifications@github.com&gt;
发送时间: 2020年9月26日(周六) 晚上10:14
收件人: "Livox-SDK/livox_camera_lidar_calibration"<livox_camera_lidar_calibration@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"cctge123"<66011@qq.com&gt;;
主题: Re: [Livox-SDK/livox_camera_lidar_calibration] 请问能否实现在loam建图的同时，对点云进行上色 (#6)




 
：）是的是的，对了，你使用projectCloud这个节点有遇到问题吗，详细的可以看我被折叠的request.
